Partial backport of D144626 to fix Decl merging with constraints
This is a partial backport of the changes to isSameEntity from commit
https://github.com/llvm/llvm-project/commit/2408f97652caadf733a879e1d7d9c0702a80d609
(which lives in a different file in LLVM 13 and was moved to ASTContext
at a later point). The gist of the change is that during template
instantiation, the constraint / requires clause also gets instantiated
and potentially changed. This means that if a function with constraints
is used in one module, but included as-is in another, the two of them
could not be merged.

This change fixes the following error seen on macOS 13 with C++20:
```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__iterator/reverse_iterator.h:141:23: error: 'std::reverse_iterator<std::string *>::operator->' from module 'std.iterator.__iterator.reverse_iterator' is not present in definition of 'std::reverse_iterator<std::string *>' in module 'std.iterator.__iterator.reverse_iterator'
    constexpr pointer operator->() const
                      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__iterator/reverse_iterator.h:141:23: note: declaration of 'operator->' does not match
```

Note that this particular code was recently reverted in commit
https://github.com/llvm/llvm-project/commit/aeee4ebd689171c963aa5d973e14cb6e731eb147
However, as far as I can tell, this relies on the implementation of
deferred concept instantiation which solves the problem from a different
angle, but cannot be easily backported to our copy of LLVM:
https://github.com/llvm/llvm-project/commit/babdef27c503c0bbbcc017e9f88affddda90ea4e